# Generated by Django 4.2.1 on 2023-06-13 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=40)),
                ('group_name', models.CharField(max_length=30)),
                ('Users', models.ManyToManyField(related_name='rel_users', to=settings.AUTH_USER_MODEL)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadmin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
