# Generated by Django 4.2.1 on 2023-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatbase_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbase',
            name='group_description',
            field=models.CharField(default='Sample description', max_length=50),
            preserve_default=False,
        ),
    ]
