# Generated by Django 4.2.1 on 2023-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatbase_group_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbase',
            name='keyword',
            field=models.CharField(default='bad', max_length=200),
            preserve_default=False,
        ),
    ]
