# Generated by Django 4.2.1 on 2023-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_betauser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betauser',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
