# Generated by Django 4.2.1 on 2023-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_betauser_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='betauser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='betauser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
