# Generated by Django 4.2.1 on 2023-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_betauser_is_active_betauser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betauser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='betauser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='betauser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
