# Generated by Django 4.2.1 on 2023-06-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_betauser_id_alter_betauser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betauser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
