# Generated by Django 4.2.1 on 2023-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_betauser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betauser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
