# Generated by Django 4.2.1 on 2023-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_betauser_email_alter_betauser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betauser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
