# Generated by Django 4.2.1 on 2023-06-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_betauser_is_staff_alter_betauser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betauser',
            name='pin',
        ),
    ]
