# Generated by Django 4.2.1 on 2023-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_betauser_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='betauser',
            name='Note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='betauser',
            name='profile',
            field=models.ImageField(default='profile/default.svg', upload_to='profile/'),
        ),
    ]
