# Generated by Django 4.2.1 on 2024-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_betauser_note_betauser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='betauser',
            name='language_preference',
            field=models.CharField(default='En', max_length=5, verbose_name='Language Preference'),
            preserve_default=False,
        ),
    ]
