# Generated by Django 4.2.1 on 2024-02-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_betauser_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betauser',
            name='language_preference',
            field=models.CharField(default='En', max_length=5, verbose_name='Language Preference'),
        ),
    ]
